// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxxphmjllyputfmlvrwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4eHBobWpsbHlwdXRmbWx2cndhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MjM4NDAsImV4cCI6MjA2MzQ5OTg0MH0.fX3r_IvTRdxJztOgXn98D1M_HzQVjTK7vAVnDJwGtMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);